config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :photos

  mount Shrine.upload_endpoint(:cache) => '/upload'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
# frozen_string_literal: true

class Photo < ApplicationRecord
  include ImageUploader::Attachment(:image)

  validates :name, presence: true

  validates :image, presence: true

  validates :opened_at, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photos_controller.rb
# frozen_string_literal: true

class PhotosController < ApplicationController
  before_action :set_photo, only: %i[show edit update destroy]

  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new photo_params

    if @photo.save
      redirect_to photos_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show; end

  def edit; end

  def update
    if @photo.update(photo_params)
      redirect_to photos_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @photo.destroy!

    redirect_to photos_path
  end

  private

  def photo_params
    params.require(:photo).permit(:name, :image).merge(opened_at: Time.now.utc)
  end

  def set_photo
    @photo = Photo.find params[:id]
  rescue ActiveRecord::RecordNotFound
    head :not_found
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photo Management</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jgthms/minireset.css@master/minireset.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&display=swap">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_with model: photo, class: 'form' do |f| %>
  <%= f.hidden_field :image, value: photo.cached_image_data, class: 'form__field form__field--data' %>

  <div class="form__group">
    <%= f.label :name, class: 'form__label' %>
    <%= f.text_field :name, class: 'form__field' %>
  </div>

  <% if photo.image_url.present? %>
    <div class="form__group form__group--file-upload hidden">
      <%= f.label :image, class: 'form__label' %>
      <%= f.file_field :image, class: 'form__field form__field--file' %>
    </div>

    <div class="form__image-preview-wrapper form__image-preview-wrapper--with-image">
        <%= image_tag photo.image_url, class: 'form__image-preview', height: 600 %>
    </div>
  <% else %>
    <div class="form__group form__group--file-upload">
      <%= f.label :image, class: 'form__label' %>
      <%= f.file_field :image, class: 'form__field form__field--file' %>
    </div>

    <div class="form__image-preview-wrapper">
      <img class="form__image-preview"></img>
    </div>
  <% end %>
  
  <div class="form__progress-bar"></div>

  <%= f.submit 'Confirm', class: 'form__button' %>

  <div class="form__alert form__alert--error">
    <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message  %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/photos/edit.html.erb
<main class="photo">
  <div class="photo__wrapper">
    <%= render 'photos/form', photo: @photo %>
  </div>
</main>

app/views/photos/index.html.erb
<main class="photos">
  <div class="photos__wrapper">
    <div class="photos__add">
      <%= link_to 'Add Photo', new_photo_path %>
    </div>

    <div class="photos__search">
      <label for="search">Search</label>
      <input id="search" name="search">
    </div>

    <table class="photos__table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Last modified</th>
          <th>File size</th>
          <th style="width: 113px;"></th>
        </tr>
      </thead>
      <tbody>
        <% @photos.each do |photo| %>
          <tr>
            <td>
              <div class="photos__table__name">
                <%= image_tag photo.image_url %>
                <span><%= link_to photo.name, edit_photo_path(photo) %></span>
              </div>
            </td>
            <td><%= photo.updated_at.strftime('%a %d, %Y') %></td>
            <td><%= '%d MB' % [photo.image.size / 1000] %></td>
            <td style="width: 113px;"><%= link_to 'Destroy', photo_path(photo), class: 'photos__destroy', method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</main>

app/views/photos/new.html.erb
<main class="photo">
  <div class="photo__wrapper">
    <%= render 'photos/form', photo: @photo %>
  </div>
</main>